name: Best Hotels Offer
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Best Hotels Offer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75aadb'
    - '#fcd209'
    - '#d3e4f3'
    - '#fde36c'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
