typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#75aadb'
    - '#fcd209'
    - '#d3e4f3'
    - '#fde36c'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49788
analytics:
  google: null
  facebook: null
  twitter: null
name: Best Hotels Offer
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 7888fba4-98eb-4b14-814d-11aa091f3cb0
    type: content
favicon: null
title: Best Hotels Offer
purpose: []
